name: Scrape, Transform, Train, Open Merge request

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Overwrite middlewares file in Selenium Python library
        run: |
          cp src/load/scraper/static/middlewares.py /opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/scrapy_selenium/middlewares.py || echo "Failed to copy file"

      - name: Scrape Data
        run: |
          cd src/load/scraper
          scrapy crawl beer-spider -o ../../../res/data/${GITHUB_RUN_NUMBER}raw_data.json -s CLOSESPIDER_PAGECOUNT=10
          cd ../../../

      - name: Transform Data
        run: python src/load/transform/mongo_db_import.py -u ${{ secrets.MONGODB_CONNECTIONSTRING }} -i res/data/${GITHUB_RUN_NUMBER}raw_data.json -c beer

      - name: Train Model
        run: python src/model/model.py -u ${{ secrets.MONGODB_CONNECTIONSTRING }} -p ./res/model/${GITHUB_RUN_NUMBER}

      - name: Create Branch and Pull Request
        run: |
          git checkout -b model/${GITHUB_RUN_NUMBER}
          git add --all
          git config --global user.email "dominik.gsteiger@gmail.com"
          git config --global user.name "GsteigerDominik"
          git commit -m "Trained new model after scraping"
          git push
