name: Scrape, Transform, Train, Open Merge request

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.1"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install chromewebdriver
        run: |
          wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Echo content of source file
        run: |
          echo "Content of source file:"
          cat src/load/scraper/static/middlewares.py

      - name: Echo content of destination file before overwrite
        run: |
          echo "Content of destination file before overwrite:"
          cat /opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/scrapy_selenium/middlewares.py

      - name: Overwrite middlewares file in Selenium Python library
        run: |
          cp src/load/scraper/static/middlewares.py /opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/scrapy_selenium/middlewares.py || echo "Failed to copy file"

      - name: Echo content of destination file after overwrite
        run: |
          echo "Content of destination file after overwrite:"
          cat /opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/scrapy_selenium/middlewares.py

      - name: Start Scraping
        run: |
          cd src/load/scraper
          scrapy crawl beer-spider -o ../../../res/data/raw_data.json -s CLOSESPIDER_PAGECOUNT=10
          cd ../../../

      - name: Start Python class 2
        run: python data_load/mongo_db_import.py -u ${{ secrets.MONGODB_CONNECTION }} -i ./res/data/output.json -c beer